### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by Mickroz** [kinerity/knowledgebase#1]
you can add navigation for example for the index page like so
`$this->template->assign_block_vars('navlinks', array(
				'U_VIEW_FORUM'	=> $this->helper->route('kinerity_knowledgebase_main_controller', array('mode' => 'index')),`

**Comment by kinerity** [comment]
Yes, I know this. I'll look at adding navlinks.

**Comment by Mickroz** [comment]
Yeah I didn't know your level of phpbb knowledge, and as I came across the same, I thought I share this with you ;)

**Comment by kinerity** [comment]
Added basic navlings.

**Comment by Mickroz** [comment]
nice!
