### ISSUE TITLE
many variables might have not been defined

### ISSUE THREAD

**Issue by Skouat** [kinerity/knowledgebase#15]
Hi,

In _**main_controller**_ many variables are not properly defined.

Here is a non exhaustive list:

- `$article_list` ([L241](https://github.com/kinerity/knowledgebase/blob/1.0.0-RC1/controller/main_controller.php#L241))
- `$rowset` (([L274](https://github.com/kinerity/knowledgebase/blob/1.0.0-RC1/controller/main_controller.php#L274))
- `$category_list` ([L275](https://github.com/kinerity/knowledgebase/blob/1.0.0-RC1/controller/main_controller.php#L275) & [L627](https://github.com/kinerity/knowledgebase/blob/1.0.0-RC1/controller/main_controller.php#L627))
- `$article_id` ([L496](https://github.com/kinerity/knowledgebase/blob/1.0.0-RC1/controller/main_controller.php#L496))
- `$username` ([L600](https://github.com/kinerity/knowledgebase/blob/1.0.0-RC1/controller/main_controller.php#L600) & [L747](https://github.com/kinerity/knowledgebase/blob/1.0.0-RC1/controller/main_controller.php#L747)). Same thing for `$title`, `$description` & `$text`

**Comment by kinerity** [comment]
I'm not getting errors with these (even with DEBUG enabled). Can you provide steps to reproduce the undefined vars?

**Comment by Skouat** [comment]
Hi,

I did not see your comment in June.
As I use phpStorm, the code analysis reports all vars listed in the ticket.
And, this is not because you can not see the errors that they don't exist.

E.g.
https://github.com/kinerity/knowledgebase/blob/cc9a8e9dcf31a38238490dcb2f1e38cd8b5eb39c/controller/main_controller.php#L529

$article_id could be undefined in the following case:
`$page` = `'posting'`and (`$mode` <> `'delete'` or `'edit'`)

This could happen because of 
https://github.com/kinerity/knowledgebase/blob/cc9a8e9dcf31a38238490dcb2f1e38cd8b5eb39c/controller/main_controller.php#L144

And, you can't see this error because the `if` checks the first expression (`in_array($mode, array('delete', 'edit'))`) and return `false` before testing the `$article_id`.

Switch them and checks if you get a notice or not ;)

**Comment by kinerity** [comment]
Why do I need an article_id for 'post' (the only other posting option allowed)? If the in_array() expression returns false, $article_id doesn't need to be defined since it's not in use. The other undefined vars were fixed in various commits after this ticket.
