### ISSUE TITLE
SQL ERROR

### ISSUE THREAD

**Issue by MorganKell** [kinerity/knowledgebase#18]
Hello, I've tried to install this extension. But all i get is this:

> Allgemeiner Fehler
> SQL ERROR [ mysqli ]
> 
> Unknown column 'category_description' in 'field list' [1054]
> 
> SQL
> 
> INSERT INTO forum_kb_categories (category_id, left_id, right_id, category_name, category_description, bbcode_bitfield, bbcode_options, bbcode_uid) VALUES (1, 1, 2, 'Example Category 1', 'A category description.', 'QQ==', 7, 'a9fmpm6m')
> 
> BACKTRACE
> 
> FILE: (not given by php)
> LINE: (not given by php)
> CALL: msg_handler()
> 
> FILE: [ROOT]/phpbb/db/driver/driver.php
> LINE: 999
> CALL: trigger_error()
> 
> FILE: [ROOT]/phpbb/db/driver/mysqli.php
> LINE: 193
> CALL: phpbb\db\driver\driver->sql_error()
> 
> FILE: [ROOT]/phpbb/db/driver/driver.php
> LINE: 659
> CALL: phpbb\db\driver\mysqli->sql_query()
> 
> FILE: [ROOT]/phpbb/db/driver/factory.php
> LINE: 377
> CALL: phpbb\db\driver\driver->sql_multi_insert()
> 
> FILE: [ROOT]/ext/kinerity/knowledgebase/migrations/v10x/release_0_0_1.php
> LINE: 271
> CALL: phpbb\db\driver\factory->sql_multi_insert()
> 
> FILE: (not given by php)
> LINE: (not given by php)
> CALL: kinerity\knowledgebase\migrations\v10x\release_0_0_1->insert_sample_data()
> 
> FILE: [ROOT]/phpbb/db/migrator.php
> LINE: 711
> CALL: call_user_func_array()
> 
> FILE: [ROOT]/phpbb/db/migrator.php
> LINE: 658
> CALL: phpbb\db\migrator->run_step()
> 
> FILE: [ROOT]/phpbb/db/migrator.php
> LINE: 436
> CALL: phpbb\db\migrator->process_data_step()
> 
> FILE: [ROOT]/phpbb/db/migrator.php
> LINE: 288
> CALL: phpbb\db\migrator->try_apply()
> 
> FILE: [ROOT]/phpbb/db/migrator.php
> LINE: 241
> CALL: phpbb\db\migrator->update_do()
> 
> FILE: [ROOT]/phpbb/extension/base.php
> LINE: 78
> CALL: phpbb\db\migrator->update()
> 
> FILE: [ROOT]/ext/kinerity/knowledgebase/ext.php
> LINE: 60
> CALL: phpbb\extension\base->enable_step()
> 
> FILE: [ROOT]/phpbb/extension/manager.php
> LINE: 190
> CALL: kinerity\knowledgebase\ext->enable_step()
> 
> FILE: [ROOT]/includes/acp/acp_extensions.php
> LINE: 209
> CALL: phpbb\extension\manager->enable_step()
> 
> FILE: [ROOT]/includes/functions_module.php
> LINE: 676
> CALL: acp_extensions->main()
> 
> FILE: [ROOT]/adm/index.php
> LINE: 82
> CALL: p_master->load_active()

If i try to delet the "work data" i get an error too:

> [phpBB Debug] PHP Notice: in file [ROOT]/phpbb/db/migrator.php on line 658: Undefined offset: 13

**Comment by kinerity** [comment]
Please use the validated version on the phpBB website. If you still need support, open a topic on the support page (https://www.phpbb.com/customise/db/extension/knowledge_base/support).
