### ISSUE TITLE
3.2.x compatible

### ISSUE THREAD

**Issue by Mickroz** [kinerity/knowledgebase#2]
if you add this:
`/** @var bool */
	public $is_phpbb31;
	/** @var bool */
	public $is_phpbb32;`
in __construct
`$this->is_phpbb31 = phpbb_version_compare(PHPBB_VERSION, '3.1.0@dev', '>=') && phpbb_version_compare(PHPBB_VERSION, '3.2.0@dev', '<');
		$this->is_phpbb32 = phpbb_version_compare(PHPBB_VERSION, '3.2.0@dev', '>=') && phpbb_version_compare(PHPBB_VERSION, '3.3.0@dev', '<');
$this->template->assign_vars(array(
			'IS_PHPBB31' => $this->settings->is_phpbb31,
			'IS_PHPBB32' => $this->settings->is_phpbb32,
		));`
you can use this for your link
`<li class="small-icon icon-kb" data-last-responsive="true">
	<a href="{U_KNOWLEDGE_BASE}" title="{L_KNOWLEDGE_BASE}" role="menuitem">
		<i class="icon fa fa-university" aria-hidden="true"></i>
		<span>{L_KNOWLEDGE_BASE}</span>
	</a>
</li>`
you can do the same with your all your styling.

**Comment by kinerity** [comment]
As you mentioned [https://www.phpbb.com/community/viewtopic.php?p=14559576#p14559576](here), a lot of changes are coming in 3.2 and will require a new version. Also, the they way you are advising is very hackish. Therefore, one branch will be 3.1 and one will be 3.2. As this doesn't affect the 3.1 branch, I'll go ahead and close this.

**Comment by Mickroz** [comment]
will you add a 3.2.x branch?

**Comment by kinerity** [comment]
Eventually ;)
