### ISSUE TITLE
Small issues and new language pack

### ISSUE THREAD

**Issue by LukeWCS** [kinerity/knowledgebase#21]
Hi kinerity

We want to use your Knowledge Base and I found a few small issues. 
I also want to add the language pack `de_x_sie`.

Now my question: can I send you fixes and language pack with one PR, or do you want separate PR's for fixes and language pack?

**Comment by kinerity** [comment]
Separate PRs please. I am curious what issue you're running into.

**Comment by LukeWCS** [comment]
Okay, separate PRs then.

No big deal, mainly EPV stuff, but also wrong language variable names.

**Comment by Crizz0** [comment]
Should be done via #22 and #23
