### ISSUE TITLE
admin_controller.php on line 468: Array to string conversion

### ISSUE THREAD

**Issue by Skouat** [kinerity/knowledgebase#7]
Hi,

When we have more than one category and we delete one, we facing to the folowing notice

> [phpBB Debug] PHP Notice: in file [ROOT]/ext/kinerity/knowledgebase/controller/admin_controller.php on line 468: Array to string conversion

**Comment by kinerity** [comment]
Try the latest commit. Should fix all of the issues. Let me know so I can close them.

**Comment by Skouat** [comment]
:+1:
